config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        include(("djinar.experiments.urls", "experiments"), namespace="experiments"),
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("djinar.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
    ImportError at /experiments/webcam
    cannot import name 'ORDER_PATTERN' from 'django.db.models.sql.constants'
    (/Users/brunux/opt/miniconda3/envs/djinar/lib/python3.8/site-packages/django/db/models/sql/constants.py)
    /Users/brunux/opt/miniconda3/envs/djinar/lib/python3.8/site-packages/rest_framework/filters.py, line 11, in <module>

    Looks like the DRF is not compatible with Django 3.1
    path(
        "c/",
        include(("djinar.contacts.urls", "contacts"), namespace="contacts"),
    ),
    path(
        "e/",
        include(("djinar.events.urls", "events"), namespace="events")
    ),
"""

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

djinar/events/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.EventsView.as_view(), name='index'),
    path('items', views.EventItemsView.as_view(), name='items'),
    path('items-date', views.EventItemsDateView.as_view(), name='items_date'),
    path('create', views.EventItemCreateView.as_view(), name='create'),
    path('edit/<uuid:pid>',
         views.EventItemEditView.as_view(),
         name='edit')
]

djinar/home/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

djinar/users/urls.py
from django.urls import path

from djinar.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

djinar/common/models.py
# Create your models here.

djinar/contacts/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel


class Contact(TimeStampedModel):
    """Model for managing `contact` information."""

    name = models.CharField(_("Full name"), max_length=255)
    job_title = models.CharField(_("Job title"), max_length=255)
    company = models.CharField(_("Company Name"), max_length=255)
    email = models.EmailField()
    contact_number = models.CharField(_("Contact Number"), max_length=62)
    notes = models.TextField(_("Notes"))
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    pid = models.UUIDField(default=uuid.uuid4, unique=True)

    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")
        ordering = ('-modified', )

    def __str__(self):
        return str(self.email)

djinar/experiments/models.py
from django.db import models

# Create your models here.

djinar/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

djinar/common/views.py
# Create your views here.

djinar/contacts/views.py
from django.views.generic import TemplateView
from rest_framework import filters
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveUpdateDestroyAPIView
)

from .models import Contact
from .serializers import ContactSerializer, ContactCreateSerializer


class ContactsView(TemplateView):
    """[summary]
    Serves the base web page for contacts.

    [description]
    """
    template_name = 'contacts/contacts.html'


class ContactItemsView(ListAPIView):
    """[summary]
    Gets contacts items paginated in descending order and may be
    filtered.

    [description]
    This view should return a list of contacts for the currently
    authenticated user.

    Extends:
        ListAPIView
    """
    serializer_class = ContactSerializer
    filter_backends = (filters.SearchFilter, )
    search_fields = (
        'name',
        'email',
        'company',
        'job_title',
    )

    def get_queryset(self):
        """
        Return `user` contacts only.
        """
        return Contact.objects.filter(
            owner=self.request.user
        ).order_by('-modified')


class ContactItemCreateView(CreateAPIView):
    """[summary]
    Creates a new contact item.

    [description]
    This view should validate and create a new contact item linking
    the item to the current authenticate user.

    Extends:
        CreateAPIView
    """
    serializer_class = ContactCreateSerializer

    def create(self, request, *args, **kwargs):
        request.data.update({"owner": self.request.user.pk})
        return super().create(request, *args, **kwargs)


class ContactItemEditView(RetrieveUpdateDestroyAPIView):
    """[summary]
    Edits or Deletes a contact item.

    [description]
    This View updates fields for a contact item it can also delete a
    contact item.

    Extends:
        RetrieveUpdateDestroyAPIView
    """
    serializer_class = ContactSerializer
    lookup_field = "pid"

    def get_queryset(self):
        """
        Return `user` contacts only.
        """
        return Contact.objects.filter(
            owner=self.request.user
        )

djinar/events/views.py
from datetime import datetime

from django.views.generic import TemplateView
from rest_framework import filters
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveUpdateDestroyAPIView
)

from .models import Event
from .serializers import EventSerializer, EventCreateSerializer


class EventsView(TemplateView):
    """[summary]
    Servers main events FE app.

    [description]
    """
    template_name = 'events/events.html'


class EventItemsView(ListAPIView):
    """[summary]
    Gets Events items paginated in descending order and may be
    filtered.

    [description]
    This view should return a list of Events for the currently
    authenticated user.

    Extends:
        ListAPIView
    """
    serializer_class = EventSerializer
    filter_backends = (filters.SearchFilter, )
    search_fields = (
        'title',
        'attendants__name',
        'attendants__email',
        'notes',
    )

    def get_queryset(self):
        """
        Return `user` Events only.

        Filtering is possible by init and end dates e.g.
        ?init=2019-12-31&end=2020-01-01 those dates should be in UTC.
        """
        return Event.objects.filter(
            owner=self.request.user
        ).order_by('-modified').prefetch_related('attendants')


class EventItemsDateView(ListAPIView):
    """[summary]
    Gets Events items paginated in descending order and may be
    filtered.

    [description]
    This view should return a list of Events for the currently
    authenticated user.

    Extends:
        ListAPIView
    """
    serializer_class = EventSerializer
    pagination_class = None

    def get_queryset(self):
        """
        Return `user` Events only.

        Filtering is possible by init and end dates e.g.
        ?init=2019-12-31&end=2020-01-01 those dates should be in UTC.
        """
        query_set = Event.objects.filter(
            owner=self.request.user
        ).order_by('-modified')

        # Dates should be in YYYY-MM-DD and UTC.
        initial_date = self.request.query_params.get('init', None)
        end_date = self.request.query_params.get('end', None)

        if not initial_date or not end_date:
            return Event.objects.none()

        try:
            initial_date = datetime.strptime(
                f"{initial_date} 0:0:0", "%Y-%m-%d %H:%M:%S",
            )
            end_date = datetime.strptime(
                f"{end_date} 23:59:59", "%Y-%m-%d %H:%M:%S",
            )
        except Exception:
            return Event.objects.none()

        return query_set.filter(
            date__gte=initial_date,
            date__lte=end_date
        ).prefetch_related('attendants')


class EventItemCreateView(CreateAPIView):
    """[summary]
    Creates a new Event item.

    [description]
    This view should validate and create a new Event item linking
    the item to the current authenticate user.

    Extends:
        CreateAPIView
    """
    serializer_class = EventCreateSerializer

    def create(self, request, *args, **kwargs):
        request.data.update({"owner": self.request.user.pk})
        return super().create(request, *args, **kwargs)


class EventItemEditView(RetrieveUpdateDestroyAPIView):
    """[summary]
    Edits or Deletes a Event item.

    [description]
    This View updates fields for a Event item it can also delete a
    Event item.

    Extends:
        RetrieveUpdateDestroyAPIView
    """
    serializer_class = EventCreateSerializer
    lookup_field = "pid"

    def get_queryset(self):
        """
        Return `user` Events only.
        """
        return Event.objects.filter(
            owner=self.request.user
        )

djinar/experiments/views.py
import asyncio
import json
import platform
import logging
import os
import uuid

from django.conf import settings
from django.views.generic import TemplateView, View
from django.http.response import HttpResponse
from django.utils.decorators import classonlymethod
from braces.views import CsrfExemptMixin

from av import VideoFrame
from aiortc import RTCPeerConnection, RTCSessionDescription
from aiortc.contrib.media import MediaBlackhole, MediaPlayer, MediaRecorder

from djinar.experiments.video import VideoTransformTrack


logger = logging.getLogger("pc")
pcs = set()


class WebcamView(TemplateView):
    """
    """
    template_name = 'experiments/webcam.html'


class WebcamOfferView(CsrfExemptMixin, View):
    """
    """
    @classonlymethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        view._is_coroutine = asyncio.coroutines._is_coroutine
        return view

    async def post(self, request, *args, **kwargs):
        """
        """
        params = json.loads(request.body)
        offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

        pc = RTCPeerConnection()
        pcs.add(pc)

        @pc.on("iceconnectionstatechange")
        async def on_iceconnectionstatechange():
            print("ICE connection state is %s" % pc.iceConnectionState)
            if pc.iceConnectionState == "failed":
                await pc.close()
                pcs.discard(pc)

        options = {"framerate": "30", "video_size": "640x480"}
        if platform.system() == "Darwin":
            player = MediaPlayer("default:none", format="avfoundation", options=options)
        else:
            player = MediaPlayer("/dev/video0", format="v4l2", options=options)

        await pc.setRemoteDescription(offer)
        for t in pc.getTransceivers():
            if t.kind == "audio" and player.audio:
                pc.addTrack(player.audio)
            elif t.kind == "video" and player.video:
                pc.addTrack(player.video)

        answer = await pc.createAnswer()
        await pc.setLocalDescription(answer)

        return HttpResponse(
            json.dumps({
                "sdp": pc.localDescription.sdp, "type": pc.localDescription.type
            }),
            content_type="application/json",
        )


class StreamingView(TemplateView):
    """
    """
    template_name = 'experiments/streaming.html'


class StreamingOfferView(CsrfExemptMixin, View):
    """
    """
    @classonlymethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        view._is_coroutine = asyncio.coroutines._is_coroutine
        return view

    async def post(self, request, *args, **kwargs):
        """
        """
        params = json.loads(request.body)
        offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

        pc = RTCPeerConnection()
        pc_id = "PeerConnection(%s)" % uuid.uuid4()
        pcs.add(pc)

        def log_info(msg, *args):
            logger.info(pc_id + " " + msg, *args)

        log_info("Created for %s", request.get_host())

        # prepare local media
        player = MediaPlayer(os.path.join(
            settings.BASE_DIR, "djinar/experiments/media/Scott_Holmes_-_04_-_Upbeat_Party.mp3")
        )
        # no recorder for now.
        recorder = MediaBlackhole()

        @pc.on("datachannel")
        def on_datachannel(channel):
            @channel.on("message")
            def on_message(message):
                if isinstance(message, str) and message.startswith("ping"):
                    channel.send("pong" + message[4:])

        @pc.on("iceconnectionstatechange")
        async def on_iceconnectionstatechange():
            log_info("ICE connection state is %s", pc.iceConnectionState)
            if pc.iceConnectionState == "failed":
                await pc.close()
                pcs.discard(pc)

        @pc.on("track")
        def on_track(track):
            log_info("Track %s received", track.kind)

            if track.kind == "audio":
                pc.addTrack(player.audio)
                recorder.addTrack(track)
            elif track.kind == "video":
                local_video = VideoTransformTrack(
                    track, transform=params["video_transform"]
                )
                pc.addTrack(local_video)

            @track.on("ended")
            async def on_ended():
                log_info("Track %s ended", track.kind)
                await recorder.stop()

        # handle offer
        await pc.setRemoteDescription(offer)
        await recorder.start()

        # send answer
        answer = await pc.createAnswer()
        await pc.setLocalDescription(answer)

        return HttpResponse(
            json.dumps({
                "sdp": pc.localDescription.sdp, "type": pc.localDescription.type
            }),
            content_type="application/json",
        )

djinar/home/views.py
from django.views.generic import TemplateView

# Create your views here.


class HomeView(TemplateView):
    """[summary]

    [description]

    Extends:
        TemplateView
    """
    template_name = 'home/home.html'

djinar/servers/views.py
# Create your views here.

djinar/tokens/views.py
# Create your views here.

djinar/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

djinar/templates/home/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>

  <div id="main">
    <v-app id="inspire">
      <v-app-bar
        app
        color="cyan"
        dark
      >
        <v-toolbar-side-icon>
          <v-img
            src="{% static "img/logo_small.png" %}"
            height="50px" width="50px"
          >
        </v-toolbar-side-icon>
        <v-spacer></v-spacer>
        <v-tooltip bottom>
          <template v-slot:activator="{ on }">
            <v-btn v-on="on" icon href="{% url 'home:index' %}">
              <v-icon>mdi-apps</v-icon>
            </v-btn>
          </template>
          <span>Apps</span>
        </v-tooltip>
        <v-tooltip bottom>
          <template v-slot:activator="{ on }">
            <v-btn v-on="on" icon href="">
              <v-icon>mdi-bell</v-icon>
            </v-btn>
          </template>
          <span>Notifications</span>
        </v-tooltip>
      </v-app-bar>

      <v-content
        class="mx-auto"
        max-width="500"
      >
        <v-container bg fill-height grid-list-md text-xs-center>
          <v-layout row wrap align-center>
            <v-row dense>
              <v-col
                cols="4"
              >
                <v-card>
                  <v-img
                    src="{% static "img/contacts_512.png" %}"
                    class="white--text align-end"
                    gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.5)"
                    height="200px"
                  >
                    <v-card-title v-text="'Contacts'"></v-card-title>
                  </v-img>

                  <v-card-actions>
                    <v-btn
                      color="pink"
                      href="{% url 'contacts:index' %}"
                      text
                    >
                      Explore
                    </v-btn>
                    <v-spacer></v-spacer>
                    <v-btn
                      text
                    >
                      <v-icon>mdi-account-plus-outline</v-icon>
                    </v-btn>
                  </v-card-actions>
                </v-card>
              </v-col>
              <v-col
                cols="4"
              >
                <v-card>
                  <v-img
                    src="{% static "img/calendar_512.png" %}"
                    class="white--text align-end"
                    gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.5)"
                    height="200px"
                  >
                    <v-card-title v-text="'Events'"></v-card-title>
                  </v-img>
                  <v-card-actions>
                    <v-btn
                      color="pink"
                      href="{% url 'events:index' %}"
                      text
                    >
                      Explore
                    </v-btn>
                    <v-spacer></v-spacer>
                    <v-btn
                      text
                    >
                      <v-icon>mdi-calendar-plus</v-icon>
                    </v-btn>
                  </v-card-actions>
                </v-card>
              </v-col>
              <v-col
                cols="4"
              >
                <v-card>
                  <v-img
                    src="{% static "img/account_512.png" %}"
                    class="white--text align-end"
                    gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.5)"
                    height="200px"
                  >
                    <v-card-title v-text="'Account'"></v-card-title>
                  </v-img>
                  <v-card-actions>
                    <v-btn
                      color="pink"
                      text
                    >
                      Explore
                    </v-btn>
                  </v-card-actions>
                </v-card>
              </v-col>
            </v-row>
          </v-layout>
        </v-container>
      </v-content>
      {% include "footer/footer.html" %}
    </v-app>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
  <script>
    new Vue({
      el: '#main',
      delimiters: ['[[', ']]'],
      vuetify: new Vuetify(),
      props: {
        source: String,
      }
    })
  </script>
</body>
</html>